<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5bybAu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5bybAu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY5bybAu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY5bybAu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY5bybAu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y5bybAu',
    'container.build_id' => '41810fa4',
    'container.build_time' => 1706770228,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5bybAu');
