<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_logout_main' => [[], [], [], [['text', '/logout']], [], [], []],
    'indexApp' => [[], ['_controller' => 'App\\Controller\\AppController::index'], [], [['text', '/index']], [], [], []],
    'app_cart' => [['productId'], ['_controller' => 'App\\Controller\\CartController::addToCart'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/cart/add']], [], [], []],
    'view_cart' => [[], ['_controller' => 'App\\Controller\\CartController::viewCart'], [], [['text', '/cart/view']], [], [], []],
    'adminPanel' => [[], ['_controller' => 'App\\Controller\\CrudController::showAdminPanel'], [], [['text', '/adminPanel']], [], [], []],
    'addProduct' => [[], ['_controller' => 'App\\Controller\\CrudController::addProduct'], [], [['text', '/product/add']], [], [], []],
    'deleteProduct' => [[], ['_controller' => 'App\\Controller\\CrudController::deleteProduct'], [], [['text', '/product/delete']], [], [], []],
    'deleteProductById' => [['id'], ['_controller' => 'App\\Controller\\CrudController::deleteProductById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product/delete']], [], [], []],
    'updateProduct' => [['id'], ['_controller' => 'App\\Controller\\CrudController::updateProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product/update']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::showJeans'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\AppController::index' => [[], ['_controller' => 'App\\Controller\\AppController::index'], [], [['text', '/index']], [], [], []],
    'App\Controller\CartController::addToCart' => [['productId'], ['_controller' => 'App\\Controller\\CartController::addToCart'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/cart/add']], [], [], []],
    'App\Controller\CartController::viewCart' => [[], ['_controller' => 'App\\Controller\\CartController::viewCart'], [], [['text', '/cart/view']], [], [], []],
    'App\Controller\CrudController::showAdminPanel' => [[], ['_controller' => 'App\\Controller\\CrudController::showAdminPanel'], [], [['text', '/adminPanel']], [], [], []],
    'App\Controller\CrudController::addProduct' => [[], ['_controller' => 'App\\Controller\\CrudController::addProduct'], [], [['text', '/product/add']], [], [], []],
    'App\Controller\CrudController::deleteProduct' => [[], ['_controller' => 'App\\Controller\\CrudController::deleteProduct'], [], [['text', '/product/delete']], [], [], []],
    'App\Controller\CrudController::deleteProductById' => [['id'], ['_controller' => 'App\\Controller\\CrudController::deleteProductById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product/delete']], [], [], []],
    'App\Controller\CrudController::updateProduct' => [['id'], ['_controller' => 'App\\Controller\\CrudController::updateProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product/update']], [], [], []],
    'App\Controller\LoginController::index' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'App\Controller\ProductController::showJeans' => [['id'], ['_controller' => 'App\\Controller\\ProductController::showJeans'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
];
